<?xml version="1.0" encoding="utf-8"?><Database Name="ShoeShop2" Class="ShoeShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-K6TE4RL\VANDAO;Initial Catalog=ShoeShop2;Persist Security Info=True;User ID=sa;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="ShoeShop2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" ThisKey="CategoryID" OtherKey="CategoryID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Order" Member="Orders" ThisKey="UserName" OtherKey="UserName" Type="Order" />
      <Association Name="User_PurchaseReceipt" Member="PurchaseReceipts" ThisKey="UserName" OtherKey="UserName" Type="PurchaseReceipt" />
      <Association Name="User_User_UserGroup" Member="User_UserGroups" ThisKey="UserName" OtherKey="UserName" Type="User_UserGroup" />
    </Type>
  </Table>
  <Table Name="dbo.ListScreen" Member="ListScreens">
    <Type Name="ListScreen">
      <Column Name="ScreenID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ScreenName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="ListScreen_Role" Member="Roles" ThisKey="ScreenID" OtherKey="ScreenID" Type="Role" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="OrderDetailID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
      <Association Name="Product_OrderDetail" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" ThisKey="OrderID" OtherKey="OrderID" Type="OrderDetail" />
      <Association Name="User_Order" Member="User" ThisKey="UserName" OtherKey="UserName" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ProductPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Product_OrderDetail" Member="OrderDetails" ThisKey="ProductID" OtherKey="ProductID" Type="OrderDetail" />
      <Association Name="Product_PurchaseReceiptDetail" Member="PurchaseReceiptDetails" ThisKey="ProductID" OtherKey="ProductID" Type="PurchaseReceiptDetail" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseReceiptDetails" Member="PurchaseReceiptDetails">
    <Type Name="PurchaseReceiptDetail">
      <Column Name="PReceiptID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Product_PurchaseReceiptDetail" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
      <Association Name="PurchaseReceipt_PurchaseReceiptDetail" Member="PurchaseReceipt" ThisKey="PReceiptID" OtherKey="ReceiptID" Type="PurchaseReceipt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseReceipts" Member="PurchaseReceipts">
    <Type Name="PurchaseReceipt">
      <Column Name="ReceiptID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReceiptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SupplierID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PurchaseReceipt_PurchaseReceiptDetail" Member="PurchaseReceiptDetails" ThisKey="ReceiptID" OtherKey="PReceiptID" Type="PurchaseReceiptDetail" />
      <Association Name="User_PurchaseReceipt" Member="User" ThisKey="UserName" OtherKey="UserName" Type="User" IsForeignKey="true" />
      <Association Name="Supplier_PurchaseReceipt" Member="Supplier" ThisKey="SupplierID" OtherKey="SupplierID" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="UserGroupID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ScreenID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ListScreen_Role" Member="ListScreen" ThisKey="ScreenID" OtherKey="ScreenID" Type="ListScreen" IsForeignKey="true" />
      <Association Name="UserGroup_Role" Member="UserGroup" ThisKey="UserGroupID" OtherKey="UserGroupID" Type="UserGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="SupplierID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Supplier_PurchaseReceipt" Member="PurchaseReceipts" ThisKey="SupplierID" OtherKey="SupplierID" Type="PurchaseReceipt" />
    </Type>
  </Table>
  <Table Name="dbo.User_UserGroup" Member="User_UserGroups">
    <Type Name="User_UserGroup">
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserGroupID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="User_User_UserGroup" Member="User" ThisKey="UserName" OtherKey="UserName" Type="User" IsForeignKey="true" />
      <Association Name="UserGroup_User_UserGroup" Member="UserGroup" ThisKey="UserGroupID" OtherKey="UserGroupID" Type="UserGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroup" Member="UserGroups">
    <Type Name="UserGroup">
      <Column Name="UserGroupID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserGroupName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="UserGroup_Role" Member="Roles" ThisKey="UserGroupID" OtherKey="UserGroupID" Type="Role" />
      <Association Name="UserGroup_User_UserGroup" Member="User_UserGroups" ThisKey="UserGroupID" OtherKey="UserGroupID" Type="User_UserGroup" />
    </Type>
  </Table>
</Database>